### PR TITLE
First submission for assignment1

### PR DESCRIPTION
**Pull request by VikasKBhat**
Submission for assignment 1

### CODE REVIEW

**Comment by pranavdv** [comment]
@VikasKMB 
Try these test cases for the first question:
1 2 1 2
1 1

2 1 1 2
1
1

The code is long, overcomplicated and repetitive. Redo it by considering horizontal, vertical and diagonals over the entire grid individually, not over sections.
Q2 LGTM.

**Review by pranavdv — CHANGES_REQUESTED** [review]
@VikasKMB
Try these test cases for the first question:
1 2 1 2
1 1

2 1 1 2
1
1

The code is long, overcomplicated and repetitive. Redo it by considering horizontal, vertical and diagonals over the entire grid individually, not over sections.
Q2 LGTM.

**Review by pranavdv — APPROVED** [review]
@VikasKMB 
Q1 LGTM. Good job. One thing you can note is that since n, w, m and board are global variables, it is not necessary to pass them to your function.

**Review by ZerothKing — APPROVED** [review]
LGTM, good job.

**Pull request merged**
